### ISSUE TITLE
Question about your checkpoint

### ISSUE THREAD

**Issue by ericlenny** [Ivan-Tang-3D/ViewRefer3D#7]
I download the checkpoint you mentioned by https://drive.google.com/drive/folders/1YqD7OklOl2rdXyG5aubLtEj6Jqth54Jc?usp=sharing. When I try to use your trained model to run the test.sh, I met some problems:

Traceback (most recent call last):
  File "/home/Harddisk/cc/ViewRefer3D/referit3d/scripts/train_referit3d.py", line 200, in <module>
    loaded_epoch = load_state_dicts(args.resume_path, map_location=device, model=model)
  File "/home/Harddisk/cc/ViewRefer3D/referit3d/models/utils.py", line 61, in load_state_dicts
    value.load_state_dict(checkpoint[key])
  File "/home/anaconda3/envs/viewrefer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ReferIt3DNet_transformer:
	Missing key(s) in state_dict: "language_encoder.embeddings.position_ids". 

How can I solve this problem？Thanks for your great work.

**Comment by Ivan-Tang-3D** [comment]
Have U downloaded the BERT ckpt, It seems related with language Encoder(BERT).

**Comment by ericlenny** [comment]
> Have U downloaded the BERT ckpt, It seems related with language Encoder(BERT).

Yeah I used link https://huggingface.co/bert-base-uncased/tree/main to download it

**Comment by Ivan-Tang-3D** [comment]
This parameter 'language_encoder.embeddings.position_ids' is merely related with the BERT ckpt. So u could try to load the Bert CKPT to check whether this parameter exists or even not necessary to exist

**Comment by Gentlyweep** [comment]
> This parameter 'language_encoder.embeddings.position_ids' is merely related with the BERT ckpt. So u could try to load the Bert CKPT to check whether this parameter exists or even not necessary to exist

I tried to train my own model yesterday and it worked very fine. The training process hasn't finished yet, but I think maybe not the Bert CKPT problem.

**Comment by ericlenny** [comment]
> This parameter 'language_encoder.embeddings.position_ids' is merely related with the BERT ckpt. So u could try to load the Bert CKPT to check whether this parameter exists or even not necessary to exist

I tried to train my own model yesterday and it worked very fine. The training process hasn't finished yet, but I think maybe not the Bert CKPT problem

**Comment by Ivan-Tang-3D** [comment]
> > This parameter 'language_encoder.embeddings.position_ids' is merely related with the BERT ckpt. So u could try to load the Bert CKPT to check whether this parameter exists or even not necessary to exist
> 
> I tried to train my own model yesterday and it worked very fine. The training process hasn't finished yet, but I think maybe not the Bert CKPT problem

Okay. I hope all is smooth.
